### ISSUE TITLE
Optional e.preventDefault() in handleContainerClick function

### ISSUE THREAD

**Issue by pcraig3** [wadackel/sweet-scroll#11]
Hello!

Just included your plugin in a project of mine recenty and I'm finding it really nice!  Setup is dead simple and the different easing animations are really good :)

However, I'm looking for a way to override [the `e.preventDefault()` call in `.handleContainerClick()`](https://github.com/tsuyoshiwada/sweet-scroll/blob/master/sweet-scroll.js#L1213).

Basically, I've put `data-scroll="{id}"` attributes to a bunch of `<input>`s in a large form such that clicking each input scolls to the next question.  The scrolling itself is working really well, but now clicking on an input doesn't actually select it.  When I removed, `e.preventDefault()`, everything was fine.

Is there an easy way to remove this behaviour that I haven't seen (or, failing that, would it be possible to add this in)?  

Thanks so much!

Paul

**Comment by wadackel** [comment]
Hi @pcraig3
Thank you for using this library!

I will try to add the following as an option. What do you think?

``` javascript
new SweetScroll({
  preventDefault: true, // Cancels the trigger click event.
  stopPropagation: true // Prevents further propagation of the trigger click event in the bubbling phase.
});
```

**Comment by pcraig3** [comment]
Yes, that would be perfect!

:+1: :+1:

**Comment by wadackel** [comment]
Thank you! Add option in the v0.6.0.

**Comment by wadackel** [comment]
`v0.6.0` released :+1: 
Will it work as expected?
- [tsuyoshiwada/sweet-scroll: ECMAScript2015 Friendly, dependency-free smooth scroll library.](https://github.com/tsuyoshiwada/sweet-scroll)
- [sweet-scroll](https://www.npmjs.com/package/sweet-scroll)

**Comment by pcraig3** [comment]
Yes, this is excellent!  Thanks so much :smiley:
