### ISSUE TITLE
Glitchy animation advances two sections instead of one

### ISSUE THREAD

**Issue by pcraig3** [wadackel/sweet-scroll#17]
Hiya, hope everything's alright!

So I've been playing with your plugin, and it looks like if you get the rhythm _exactly_ right, you end up with a glitchy animation that jumps two sections instead of just advancing by one section.

For example, sometimes you can get it to go:

```
1 -> 2
2 -> 3
2 -> 4  # this is the glitch
4 -> 5
```

I'm not sure if you've noticed this, but it's actually pretty hard for me to replicate consistently. 

I've put up [a demo page](http://pcraig3.ca/sweet-scroll-demo/) where you can click or press the down arrow to advance through sections.  
It seems like if you try to go to the next section _a tiny bit before_ the transition is fully finished, you can get it to snap backwards really quickly and then advance two sections at once.  

Maybe an event queue or something could mitigate the issue?

Not too invested in this one, to be honest.  Just bringing it to your attention if you've not noticed it before.

**Comment by wadackel** [comment]
Hi, @pcraig3.
Thanks for issues and demo pages.

I confirmed glitchy animation.

It will be bugfix in the next version, Please wait a moment now.

**Comment by wadackel** [comment]
A bug fix version has been released.
Please try it if you have the chance 👍

**Comment by pcraig3** [comment]
Hey @tsuyoshiwada, I've just tried it and it looks good! 

I've not been able to replicate the error through manual testing, so I'm happy to call it fixed. :+1: 

As a small aside, I wonder if you wouldn't mind quickly explaining what the problem was and how you fixed it.  I've had a look at [the commit referenced](https://github.com/tsuyoshiwada/sweet-scroll/commit/dac2433dbcf733bf690c414c609418176ed4e09b), but just looking at how the code changed I don't really understand what the problem was.  No obligation, of course -- I'm just curious.

Thanks anyway for making the fix!

For reference:
- [Scroll demo 1 [glitchy]](http://pcraig3.ca/sweet-scroll-demo-old/)
- [Scroll demo 2 [fixed]](http://pcraig3.ca/sweet-scroll-demo/) 

<sub>(Sorry for the delay as I've been on vacation. :sunny: :palm_tree:)</sub>
