### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by davidspiess** [wadackel/sweet-scroll#21]
Where can i see what features you added, bugs you fixed between releases?

**Comment by wadackel** [comment]
Hi @davidspiess, Thanks for issue.

At the moment, Changelog does not exist.
Would you please check the closed Issues or commit log?

In the near future, I will try to add the Changelog.

**Comment by wadackel** [comment]
Changelog added. [CHANGELOG.md](https://github.com/tsuyoshiwada/sweet-scroll/blob/master/CHANGELOG.md)

Please check when you have time.
Thanks!

**Comment by davidspiess** [comment]
Thank you, looks awesome! :)
