### ISSUE TITLE
Chrome/Safari: scroll doesn't fire when browser zoom is less than 100%

### ISSUE THREAD

**Issue by deetwentytwo** [wadackel/sweet-scroll#23]
Found this odd issue when browser is zoomed out:
- When page loads @ zoom 100%, scroll works properly
- When page loads @ zoom 100% and you subsequently zoom out (90% or less), it still works fine
- When page loads @ zoom <= 90%, then the scroll doesn't fire

Test page: http://tsuyoshiwada.github.io/sweet-scroll/
Browsers: Chrome 51 and Safari 9

**Comment by wadackel** [comment]
Hi @deetwentytwo. Thanks for issue.

I confirmed of the zoom out bug.
I think the cause of the investigation and want to try a fix.

**Comment by wadackel** [comment]
I tried to bugfix. (new release `v1.0.3`)

Please check when you have time.
http://tsuyoshiwada.github.io/sweet-scroll/

**Comment by deetwentytwo** [comment]
Fixed! Thank you :)

**Comment by wadackel** [comment]
I'm glad!
Thank you, too!
