### ISSUE TITLE
If scroll position is 0 on load, initialized is never called...?

### ISSUE THREAD

**Issue by lonepalmus** [wadackel/sweet-scroll#26]
At least I think thats whats going on... I tried loading the page with a scroll position greater than 0 and everything works great.

I experienced this in the latest version, so reverted back to 1.0.0, where it works as expected. (Haven't tested the versions inbetween)

**Comment by wadackel** [comment]
Hi @lonepalmus, Thank you for Issues.

I could not check the problem...😢 
Is it possible for you to present a minimum of sample code?

**Comment by lonepalmus** [comment]
So, I included the npm package, and the following is my code example. I've also included a 5 seconds video showing the issue :)

http://pastebin.com/45Y355WA

http://ge.tt/7SQ6R6d2

as mentioned before, 1.0.0 works fine.

**Comment by wadackel** [comment]
Thank you for sample code and demo movie :-)
I will investigate the cause and try fix in next version.

**Comment by wadackel** [comment]
I'm sorry...
I received sample code tried, but was unable to reproduces bug.
Tried environment is follows.
- sweet-scroll.js v1.0.3
- Chrome 52.0.2743.116 (64-bit)

**Comment by lonepalmus** [comment]
ok, thanks for trying anyways :) Both my colleague and I experienced it, but not consistently, so if no one else complains, its probably not that big a problem :)

**Comment by wadackel** [comment]
Thanks for reply. Also please contact us if there is a problem😄 !
