### ISSUE TITLE
Sweet Scroll tween is undefined in IE11

### ISSUE THREAD

**Issue by nicolechung** [wadackel/sweet-scroll#29]
<img width="1266" alt="screen shot 2016-08-23 at 1 56 07 pm" src="https://cloud.githubusercontent.com/assets/771170/17903433/717247fe-6939-11e6-90d4-f4f8d2905409.png">

The tween appears to be `undefined` in IE 11. This is causing scrolling to not work.

This is in IE 11 Edge mode.

**Comment by wadackel** [comment]
Sorry for the late response.

I also tried to check in IE11 (Edge mode).
But, it was not possible to reproduce the error in this environment...:cry:

Do Container has been acquired correctly on IE11?
(I thought that initialized method has not been called.)

Thanks.

**Comment by wadackel** [comment]
This Issue will close once, but please reopen if there is a problem 🙇
