### ISSUE TITLE
Isomorphic

### ISSUE THREAD

**Issue by fluse** [wadackel/sweet-scroll#35]
Sweet Scroll not working on isomorphic apps.

window and document is not defined.

This, will help:
```javascript
let tmpWin = null;
let tmpDoc = null;

if (typeof window !== "undefined") {
  tmpWin = window;
}

if (typeof document !== "undefined") {
  tmpDoc = document;
}

export const win = tmpWin;
export const doc = tmpDoc;
````

window, document, navigator, requestAnimationFrame, onWheel

**Comment by wadackel** [comment]
Thanks for issues and advise :)
I will correspond with isomorhic(universal) app in next version :muscle:

It will be released this weekend.

**Comment by fluse** [comment]
navigator is not defined too! Can you hurry up with a new version? ;-)

requestAnimationFrame will bring a problem too, on node js environment

onWheel too

**Comment by wadackel** [comment]
We will do our best :ok_hand: !

**Comment by wadackel** [comment]
I released a [new version](https://www.npmjs.com/package/sweet-scroll) :tada:

**Comment by fluse** [comment]
thanks <3
