### ISSUE TITLE
Add Bower Support ?

### ISSUE THREAD

**Issue by sylvainbaronnet** [wadackel/sweet-scroll#37]
Add bower Support ?

https://bower.io/docs/creating-packages/

**Comment by wadackel** [comment]
Hi @sylvainbaronnet, Thanks for Issues.

Sorry, There is no plan to support to Bower.
We think that front-end resources should be aggregated into npm.

**Comment by sylvainbaronnet** [comment]
I understand but it can be both, no ?

**Comment by wadackel** [comment]
Bower became Deprecated the other day.
Therefore, I think that we will not respond in the future.

https://github.com/bower/bower/issues/2298
