### ISSUE TITLE
1.5 / getZoomLevel may result in scrollTop===0 and no scrolling when dev tools are open

### ISSUE THREAD

**Issue by adamkarminski** [wadackel/sweet-scroll#38]
Hi @tsuyoshiwada!

Thanks for developing and maintaining the lib! I looked for an ES6 ready lib for scrolling for a long time! :)

Though I found a funny issue today. I was trying to figure out why my container is `null` on one view I'm working on, while being scrollable on another. My investigation led me to the `getScrollable` function. I see what you do there, trying to make sure the container is scrollable, though I don't fully understand why the scrolling should not work if a window zoom is bigger than `1.5`. :)

Anyway - because of the way a zoom level is calculated in `getZoomLevel`, having the dev tools open aside makes the `outerWidth/innerWidth` ratio bigger than `1`. And the moment it gets bigger than `1.5` - the `scrollTop` set on the element gets rounded to `0` which results in no scrolling behaviour. :)

I might not be aware of all factors that led you to the decision of disabling scroll for zoom levels bigger than 1.5, but the first thing that came to my head is to compare the zoom level calculated from `outerWidth/innerWidth` with `outerHeight/innerHeight`.

For now, a temporary solution I use is to change `scrollTop` of the container from `0` to `1` before calling the Sweet Scroll.

Let me know if you need more info! Thanks again for working on the lib! ;)

**Comment by wadackel** [comment]
Hi, @adamkarminski. Thanks for Issues :smiley:

dev tools == Chrome Dev Tools ??

It is helpful if you can tell me the smallest code that can reproduce Issue, if possible.
Thanks.

**Comment by adamkarminski** [comment]
Hi @tsuyoshiwada! Sure, I'll do my best to provide a fiddle as soon as we're done with the upcoming release on Saturday (yay!). ;)

But before, if it's helpful - I was able to reproduce it in any situation in which:
- `container.scrollTop === 0`
- a Sweet Scroll should happen
- CDT took more than 33.3(3)% of the screen, resulting in `outerWidth/innerWidth > 1.5`. ;)

And yes - dev tools === Chrome Dev Tools. ;)

If you won't be able to reproduce the issue, I'll try to provide the snippet next week. :)

Have a good day!

**Comment by amritk** [comment]
I sort of have the same issue, for some reason container seems to be null on this one page, even when the element exists. I think it has to do with scrollHeight being 0, once scroll height is > 0 then it works.
```
this.container = document.getElementById('explore-list-container')
console.log(this.container.scrollHeight) // 0
setTimeout(() => {
    this.sweetScroll = new SweetScroll({
        duration: 500,
        easing: 'easeInOutExpo'
    }, this.container)
    console.log(this.container.scrollHeight) // 1179
}, 0)
```
So that's why the timeout works

**Comment by h6ah4i** [comment]
@tsuyoshiwada Hi. Any progress on this issue? I've also faced to this and it's very annoying during debugging 😞 

## Proposed solution

Because there is no reliable way to get the actual zoom level, so we should use completely different approach. 

```typescript
// FYI: this method does not require a temporary `div` anymore!
const computedStyle = window.getComputedStyle($el);
const canScrollX = (computedStyle['overflow-x'] == 'auto' || computedStyle['overflow-x'] == 'scroll');
const canScrollY = (computedStyle['overflow-y'] == 'auto' || computedStyle['overflow-y'] == 'scroll');
```

Related
- https://stackoverflow.com/a/36900407


## Proposed solution 2

I do not recommend this approach, but just for workaround of this issue.

```diff
- $el[method] = 1.5 / zoom;
+ $el[method] = Math.max(1, 1.5 / zoom);
```

**Comment by wadackel** [comment]
Hi @h6ah4i, Unfortunately there is no progress of this Issue ....

The content you suggested looks good :smiley:
I will try releasing the alpha version with the suggested content :+1:

**Comment by wadackel** [comment]
`overflow` in` html` or `body` may return a value such as `visible`.
It depends on the value of `overflow` and may not actually be scrollable.

I would like to fix it using the contents of `Proposed solution 2` :hand:

**Comment by wadackel** [comment]
Released as `v3.0.1` :tada:
Please confirm it when you have time :pray:

**Comment by h6ah4i** [comment]
@tsuyoshiwada Sorry for the very late response 😞 I've confirmed that the problem has been solved for me 👍

**Comment by wadackel** [comment]
@h6ah4i 
I'm glad that the problem could be solved successfully :pray:
Please report if there is something again.
