### ISSUE TITLE
How to scroll inside a container

### ISSUE THREAD

**Issue by sylvainbaronnet** [wadackel/sweet-scroll#39]
How to scroll inside a div element ?

**Comment by wadackel** [comment]
Hi @sylvainbaronnet.

[Specifies the container](https://github.com/tsuyoshiwada/sweet-scroll#specifies-the-container) will be helpful.
Actual worked can be confirmed [here](http://tsuyoshiwada.github.io/sweet-scroll/container.html).

**Comment by sylvainbaronnet** [comment]
Thanks! I don't know why I missed that.
