### ISSUE TITLE
Usage with JSX (React.js)

### ISSUE THREAD

**Issue by vimyum** [wadackel/sweet-scroll#42]
Hi @tsuyoshiwada.
Thanks a lot this awesome library.

When I use the `sweet-scroll` with JSX, `data-scroll` attribute is convert to `data-scroll="true"` so that `href` variable in below code would be `"true"`. This occurs an incorrect behavior of `this.to(distance)` method.

```js
const data = el.getAttribute("data-scroll");
const dataOptions = this.parseDataOptions(el);
const href = data || el.getAttribute("href");
``` 

Why don't you  check whether `data-scroll` is `"true"` or `URL fragment`.　
As an alternative way, I guess specifying the value of `data-scroll` works well as bellow.
```html
<a href="#feature" data-scroll="#feature">jump</a> <!-- JSX -->
```
How about adding this usage to `README.md`.

**Comment by wadackel** [comment]
Hi @vimyum, Thank you for Issues :+1:

`data-scroll =" # feature "` Although there is no problem, you can work similarly by specifying a empty string like `data-scroll =""` as a workaround.

It is PR welcome of document update :smile:

**Comment by vimyum** [comment]
Thank you for your reply.
I understand the workaround in JSX. I will try to make a PR of document when I have a time :smile:
